extends:
  - "@commitlint/config-conventional"

rules:
  type-enum:
    - 2
    - always
    - - feat # New feature
      - fix # Bug fix
      - docs # Documentation
      - style # Code style changes
      - refactor # Code refactoring
      - perf # Performance improvements
      - test # Tests
      - build # Build system
      - ci # CI/CD
      - chore # Maintenance
      - revert # Revert changes

  scope-empty:
    - 0

  body-max-line-length:
    - 2
    - always
    - 100
