apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-ci-cd
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-ci-cd
  template:
    metadata:
      labels:
        app: golang-ci-cd
    spec:
      containers:
        - name: golang-ci-cd
          image: ghcr.io/yassinebk/golang-ci-cd:latest
          ports:
            - containerPort: 8080
