apiVersion: v1
kind: Service
metadata:
  name: golang-ci-cd
  namespace: default
spec:
  selector:
    app: your-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
